In [1]:
import sqlite3
import pandas as pd
import numpy as np

In [2]:
conn = sqlite3.connect('./data/database.sqlite')

if conn:
    print("Connection successful")
else:
    print("Connection failed")

# Close the connection
conn.close()

Connection successful

In [4]:
# Connect to the database
conn = sqlite3.connect('./data/database.sqlite')

# Create a cursor
cur = conn.cursor()

# Get the names of all tables in the database
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
table_names = [row[0] for row in cur.fetchall()]

# Print the names and descriptions of all tables
for table_name in table_names:
    print("Table name:", table_name)
    print("Description:")
    cur.execute("PRAGMA table_info('" + table_name + "')")
    columns = cur.fetchall()
    for column in columns:
        print(column[1], column[2])
    print()

# Close the cursor and connection
cur.close()
conn.close()

Table name: Crosswalk2015
Description:
State TEXT
DentalPlan TEXT
PlanID_2014 TEXT
IssuerID_2014 INTEGER
MultistatePlan_2014 TEXT
MetalLevel_2014 TEXT
ChildAdultOnly_2014 INTEGER
FIPSCode INTEGER
ZipCode INTEGER
CrosswalkLevel INTEGER
ReasonForCrosswalk INTEGER
PlanID_2015 TEXT
IssuerID_2015 INTEGER
MultistatePlan_2015 TEXT
MetalLevel_2015 TEXT
ChildAdultOnly_2015 TEXT
AgeOffPlanID_2015 TEXT
IssuerID_AgeOff2015 INTEGER
MultistatePlan_AgeOff2015 TEXT
MetalLevel_AgeOff2015 TEXT
ChildAdultOnly_AgeOff2015 TEXT

Table name: Crosswalk2016
Description:
State TEXT
DentalPlan TEXT
PlanID_2015 TEXT
IssuerID_2015 INTEGER
MultistatePlan_2015 TEXT
MetalLevel_2015 TEXT
ChildAdultOnly_2015 INTEGER
FIPSCode INTEGER
ZipCode INTEGER
CrosswalkLevel INTEGER
ReasonForCrosswalk INTEGER
PlanID_2016 TEXT
IssuerID_2016 INTEGER
MultistatePlan_2016 TEXT
MetalLevel_2016 TEXT
ChildAdultOnly_2016 TEXT
AgeOffPlanID_2016 TEXT
IssuerID_AgeOff2016 INTEGER
MultistatePlan_AgeOff2016 TEXT
MetalLevel_AgeOff2016 TEXT
ChildAdultOnly_AgeOff2016 TEXT

Table name: PlanAttributes
Description:
AVCalculatorOutputNumber TEXT
BeginPrimaryCareCostSharingAfterNumberOfVisits INTEGER
BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays INTEGER
BenefitPackageId INTEGER
BusinessYear INTEGER
CSRVariationType TEXT
ChildOnlyOffering TEXT
ChildOnlyPlanId TEXT
CompositeRatingOffered TEXT
DEHBCombInnOonFamilyMOOP TEXT
DEHBCombInnOonFamilyPerGroupMOOP TEXT
DEHBCombInnOonFamilyPerPersonMOOP TEXT
DEHBCombInnOonIndividualMOOP TEXT
DEHBDedCombInnOonFamily TEXT
DEHBDedCombInnOonFamilyPerGroup TEXT
DEHBDedCombInnOonFamilyPerPerson TEXT
DEHBDedCombInnOonIndividual TEXT
DEHBDedInnTier1Coinsurance TEXT
DEHBDedInnTier1Family TEXT
DEHBDedInnTier1FamilyPerGroup TEXT
DEHBDedInnTier1FamilyPerPerson TEXT
DEHBDedInnTier1Individual TEXT
DEHBDedInnTier2Coinsurance TEXT
DEHBDedInnTier2Family TEXT
DEHBDedInnTier2FamilyPerGroup TEXT
DEHBDedInnTier2FamilyPerPerson TEXT
DEHBDedInnTier2Individual TEXT
DEHBDedOutOfNetFamily TEXT
DEHBDedOutOfNetFamilyPerGroup TEXT
DEHBDedOutOfNetFamilyPerPerson TEXT
DEHBDedOutOfNetIndividual TEXT
DEHBInnTier1FamilyMOOP TEXT
DEHBInnTier1FamilyPerGroupMOOP TEXT
DEHBInnTier1FamilyPerPersonMOOP TEXT
DEHBInnTier1IndividualMOOP TEXT
DEHBInnTier2FamilyMOOP NUMERIC
DEHBInnTier2FamilyPerGroupMOOP NUMERIC
DEHBInnTier2FamilyPerPersonMOOP NUMERIC
DEHBInnTier2IndividualMOOP NUMERIC
DEHBOutOfNetFamilyMOOP TEXT
DEHBOutOfNetFamilyPerGroupMOOP TEXT
DEHBOutOfNetFamilyPerPersonMOOP TEXT
DEHBOutOfNetIndividualMOOP TEXT
DentalOnlyPlan TEXT
DiseaseManagementProgramsOffered TEXT
EHBPediatricDentalApportionmentQuantity TEXT
EHBPercentPremiumS4 NUMERIC
EHBPercentTotalPremium NUMERIC
FirstTierUtilization TEXT
FormularyId TEXT
FormularyURL TEXT
HIOSProductId TEXT
HPID NUMERIC
HSAOrHRAEmployerContribution TEXT
HSAOrHRAEmployerContributionAmount TEXT
ImportDate TEXT
IndianPlanVariationEstimatedAdvancedPaymentAmountPerEnrollee TEXT
InpatientCopaymentMaximumDays INTEGER
IsGuaranteedRate TEXT
IsHSAEligible TEXT
IsNewPlan TEXT
IsNoticeRequiredForPregnancy TEXT
IsReferralRequiredForSpecialist TEXT
IssuerActuarialValue TEXT
IssuerId INTEGER
IssuerId2 INTEGER
MEHBCombInnOonFamilyMOOP TEXT
MEHBCombInnOonFamilyPerGroupMOOP TEXT
MEHBCombInnOonFamilyPerPersonMOOP TEXT
MEHBCombInnOonIndividualMOOP TEXT
MEHBDedCombInnOonFamily TEXT
MEHBDedCombInnOonFamilyPerGroup TEXT
MEHBDedCombInnOonFamilyPerPerson TEXT
MEHBDedCombInnOonIndividual TEXT
MEHBDedInnTier1Coinsurance TEXT
MEHBDedInnTier1Family TEXT
MEHBDedInnTier1FamilyPerGroup TEXT
MEHBDedInnTier1FamilyPerPerson TEXT
MEHBDedInnTier1Individual TEXT
MEHBDedInnTier2Coinsurance TEXT
MEHBDedInnTier2Family TEXT
MEHBDedInnTier2FamilyPerGroup TEXT
MEHBDedInnTier2FamilyPerPerson TEXT
MEHBDedInnTier2Individual TEXT
MEHBDedOutOfNetFamily TEXT
MEHBDedOutOfNetFamilyPerGroup TEXT
MEHBDedOutOfNetFamilyPerPerson TEXT
MEHBDedOutOfNetIndividual TEXT
MEHBInnTier1FamilyMOOP TEXT
MEHBInnTier1FamilyPerGroupMOOP TEXT
MEHBInnTier1FamilyPerPersonMOOP TEXT
MEHBInnTier1IndividualMOOP TEXT
MEHBInnTier2FamilyMOOP TEXT
MEHBInnTier2FamilyPerGroupMOOP TEXT
MEHBInnTier2FamilyPerPersonMOOP TEXT
MEHBInnTier2IndividualMOOP TEXT
MEHBOutOfNetFamilyMOOP TEXT
MEHBOutOfNetFamilyPerGroupMOOP TEXT
MEHBOutOfNetFamilyPerPersonMOOP TEXT
MEHBOutOfNetIndividualMOOP TEXT
MarketCoverage TEXT
MedicalDrugDeductiblesIntegrated TEXT
MedicalDrugMaximumOutofPocketIntegrated TEXT
MetalLevel TEXT
MultipleInNetworkTiers TEXT
NationalNetwork TEXT
NetworkId TEXT
OutOfCountryCoverage TEXT
OutOfCountryCoverageDescription TEXT
OutOfServiceAreaCoverage TEXT
OutOfServiceAreaCoverageDescription TEXT
PlanBrochure TEXT
PlanEffictiveDate TEXT
PlanExpirationDate TEXT
PlanId TEXT
PlanLevelExclusions TEXT
PlanMarketingName TEXT
PlanType TEXT
QHPNonQHPTypeId TEXT
RowNumber INTEGER
SBCHavingDiabetesCoinsurance TEXT
SBCHavingDiabetesCopayment TEXT
SBCHavingDiabetesDeductible TEXT
SBCHavingDiabetesLimit TEXT
SBCHavingaBabyCoinsurance TEXT
SBCHavingaBabyCopayment TEXT
SBCHavingaBabyDeductible TEXT
SBCHavingaBabyLimit TEXT
SecondTierUtilization TEXT
ServiceAreaId TEXT
SourceName TEXT
SpecialistRequiringReferral TEXT
SpecialtyDrugMaximumCoinsurance TEXT
StandardComponentId TEXT
StateCode TEXT
StateCode2 TEXT
TEHBCombInnOonFamilyMOOP TEXT
TEHBCombInnOonFamilyPerGroupMOOP TEXT
TEHBCombInnOonFamilyPerPersonMOOP TEXT
TEHBCombInnOonIndividualMOOP TEXT
TEHBDedCombInnOonFamily TEXT
TEHBDedCombInnOonFamilyPerGroup TEXT
TEHBDedCombInnOonFamilyPerPerson TEXT
TEHBDedCombInnOonIndividual TEXT
TEHBDedInnTier1Coinsurance TEXT
TEHBDedInnTier1Family TEXT
TEHBDedInnTier1FamilyPerGroup TEXT
TEHBDedInnTier1FamilyPerPerson TEXT
TEHBDedInnTier1Individual TEXT
TEHBDedInnTier2Coinsurance TEXT
TEHBDedInnTier2Family TEXT
TEHBDedInnTier2FamilyPerGroup TEXT
TEHBDedInnTier2FamilyPerPerson TEXT
TEHBDedInnTier2Individual TEXT
TEHBDedOutOfNetFamily TEXT
TEHBDedOutOfNetFamilyPerGroup TEXT
TEHBDedOutOfNetFamilyPerPerson TEXT
TEHBDedOutOfNetIndividual TEXT
TEHBInnTier1FamilyMOOP TEXT
TEHBInnTier1FamilyPerGroupMOOP TEXT
TEHBInnTier1FamilyPerPersonMOOP TEXT
TEHBInnTier1IndividualMOOP TEXT
TEHBInnTier2FamilyMOOP TEXT
TEHBInnTier2FamilyPerGroupMOOP TEXT
TEHBInnTier2FamilyPerPersonMOOP TEXT
TEHBInnTier2IndividualMOOP TEXT
TEHBOutOfNetFamilyMOOP TEXT
TEHBOutOfNetFamilyPerGroupMOOP TEXT
TEHBOutOfNetFamilyPerPersonMOOP TEXT
TEHBOutOfNetIndividualMOOP TEXT
TIN TEXT
URLForEnrollmentPayment TEXT
URLForSummaryofBenefitsCoverage TEXT
UniquePlanDesign TEXT
VersionNum INTEGER
WellnessProgramOffered TEXT

Table name: Network
Description:
BusinessYear INTEGER
StateCode TEXT
IssuerId INTEGER
SourceName TEXT
VersionNum INTEGER
ImportDate TEXT
IssuerId2 INTEGER
StateCode2 TEXT
NetworkName TEXT
NetworkId TEXT
NetworkURL TEXT
RowNumber INTEGER
MarketCoverage TEXT
DentalOnlyPlan TEXT

Table name: BenefitsCostSharing
Description:
BenefitName TEXT
BusinessYear INTEGER
CoinsInnTier1 TEXT
CoinsInnTier2 TEXT
CoinsOutofNet TEXT
CopayInnTier1 TEXT
CopayInnTier2 TEXT
CopayOutofNet TEXT
EHBVarReason TEXT
Exclusions TEXT
Explanation TEXT
ImportDate TEXT
IsCovered TEXT
IsEHB TEXT
IsExclFromInnMOOP TEXT
IsExclFromOonMOOP TEXT
IsStateMandate TEXT
IsSubjToDedTier1 TEXT
IsSubjToDedTier2 TEXT
IssuerId INTEGER
IssuerId2 INTEGER
LimitQty NUMERIC
LimitUnit TEXT
MinimumStay NUMERIC
PlanId TEXT
QuantLimitOnSvc TEXT
RowNumber INTEGER
SourceName TEXT
StandardComponentId TEXT
StateCode TEXT
StateCode2 TEXT
VersionNum INTEGER

Table name: ServiceArea
Description:
BusinessYear INTEGER
StateCode TEXT
IssuerId INTEGER
SourceName TEXT
VersionNum INTEGER
ImportDate TEXT
IssuerId2 INTEGER
StateCode2 TEXT
ServiceAreaId TEXT
ServiceAreaName TEXT
CoverEntireState TEXT
County NUMERIC
PartialCounty TEXT
ZipCodes TEXT
PartialCountyJustification TEXT
RowNumber INTEGER
MarketCoverage TEXT
DentalOnlyPlan TEXT

Table name: BusinessRules
Description:
BusinessYear INTEGER
StateCode TEXT
IssuerId INTEGER
SourceName TEXT
VersionNum INTEGER
ImportDate TEXT
IssuerId2 INTEGER
TIN TEXT
ProductId TEXT
StandardComponentId TEXT
EnrolleeContractRateDeterminationRule TEXT
TwoParentFamilyMaxDependentsRule TEXT
SingleParentFamilyMaxDependentsRule TEXT
DependentMaximumAgRule TEXT
ChildrenOnlyContractMaxChildrenRule TEXT
DomesticPartnerAsSpouseIndicator TEXT
SameSexPartnerAsSpouseIndicator TEXT
AgeDeterminationRule TEXT
MinimumTobaccoFreeMonthsRule TEXT
CohabitationRule TEXT
RowNumber INTEGER
MarketCoverage TEXT
DentalOnlyPlan TEXT

Table name: Rate
Description:
BusinessYear INTEGER
StateCode TEXT
IssuerId INTEGER
SourceName TEXT
VersionNum INTEGER
ImportDate TEXT
IssuerId2 INTEGER
FederalTIN TEXT
RateEffectiveDate TEXT
RateExpirationDate TEXT
PlanId TEXT
RatingAreaId TEXT
Tobacco TEXT
Age TEXT
IndividualRate NUMERIC
IndividualTobaccoRate NUMERIC
Couple NUMERIC
PrimarySubscriberAndOneDependent NUMERIC
PrimarySubscriberAndTwoDependents NUMERIC
PrimarySubscriberAndThreeOrMoreDependents NUMERIC
CoupleAndOneDependent NUMERIC
CoupleAndTwoDependents NUMERIC
CoupleAndThreeOrMoreDependents NUMERIC
RowNumber INTEGER

## Load data into pandas

In [5]:
import pandas as pd
conn = sqlite3.connect('./data/database.sqlite')
#retrieve the query results into a pandas dataframe
df = pd.read_sql_query("select * from Crosswalk2015;", conn)

#print the dataframe
df

,State,DentalPlan,PlanID_2014,IssuerID_2014,MultistatePlan_2014,MetalLevel_2014,ChildAdultOnly_2014,FIPSCode,ZipCode,CrosswalkLevel,...,PlanID_2015,IssuerID_2015,MultistatePlan_2015,MetalLevel_2015,ChildAdultOnly_2015,AgeOffPlanID_2015,IssuerID_AgeOff2015,MultistatePlan_AgeOff2015,MetalLevel_AgeOff2015,ChildAdultOnly_AgeOff2015
0,AK,Y,21989AK0010001,21989,N,Low,0,2013,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
1,AK,Y,21989AK0010001,21989,N,Low,0,2016,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
2,AK,Y,21989AK0010001,21989,N,Low,0,2020,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
3,AK,Y,21989AK0010001,21989,N,Low,0,2050,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
4,AK,Y,21989AK0010001,21989,N,Low,0,2060,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132500,WY,Y,83964WY0010004,83964,N,High,0,56037,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X
132501,WY,Y,83964WY0010004,83964,N,High,0,56039,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X
132502,WY,Y,83964WY0010004,83964,N,High,0,56041,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X
132503,WY,Y,83964WY0010004,83964,N,High,0,56043,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X
132504,WY,Y,83964WY0010004,83964,N,High,0,56045,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X